service: graphql-dynamodb

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    HEROES_TABLE: Heroes
    SKILLS_TABLE: Skill
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}
    DYNAMODB_PORT: ${env:DYNAMODB_PORT, "4569"}

    
plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      host: ${self:provider.environment.LOCALSTACK_HOST}
      port: ${self:provider.environment.DYNAMODB_PORT}
      migrate: true
      noStart: true
      seed: true
    seed:
      
    

functions:
  hello:
    handler: handler.hello
