service: auth-sls

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline


functions:
  login:
    handler: src/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  heroes-public:
    handler: src/getHeroes.public
    events:
      - http:
          path: public
          method: get
          cors:
              origins:
                - '*'
              headers:
                - Content-Type
                - Authorization

  heroes-private:
    handler: src/getHeroes.private
    events:
      - http:
          path: private
          method: get
          cors:
              origins:
                - '*'
              headers:
                - Content-Type
                - Authorization
              