
service: trigger-dynamodb

provider:
  name: aws
  runtime: nodejs12.x


functions:
  hero-insert:
    handler: handler.heroesInsert
    events:
      - http:
          path: heroes
          method: post
          cors: true
